@host=http://localhost:3000

POST {{host}}/passRecord
Content-Type: application/json

{
    "name": "google",
    "userName": "johnDoe",
    "password": "ultraStrongPass",
    "loginLink": "google.com"
}