@host=http://localhost:4000

GET {{host}}/passRecord/634fb34bca67cdb7d9054d4a
Content-Type: application/json
Cookie: connect.sid=s%3AvsGsdvxsSv07_PXDQT25YH1zKOuAW1Vu.A%2FzTx7KaMAxbLSvTYMQGgkLJFUhciYO95L4Ky%2FBQtAw